# Generated by Django 5.2 on 2025-07-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(help_text='Nombre del cliente que realiza el pedido.', max_length=100)),
                ('variante', models.CharField(choices=[('Carnívoro', 'Carnívoro'), ('Vegetariano', 'Vegetariano'), ('Saludable', 'Saludable')], help_text='Tipo de variante del cono (Carnívoro, Vegetariano o Saludable).', max_length=20)),
                ('toppings', models.JSONField(default=list, help_text='Lista de toppings adicionales para el cono.')),
                ('tamanio_cono', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], help_text='Tamaño del cono (Pequeño, Mediano o Grande).', max_length=10)),
                ('fecha_pedido', models.DateField(auto_now_add=True, help_text='Fecha en que se realizó el pedido.')),
            ],
            options={
                'verbose_name': 'Pedido de Cono',
                'verbose_name_plural': 'Pedidos de Conos',
                'ordering': ['-fecha_pedido'],
            },
        ),
    ]
