# Generated by Django 5.2 on 2025-07-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocono',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pedidocono',
            name='ingredientes',
            field=models.JSONField(default=list, help_text='Lista de ingredientes adicionales para el cono.'),
        ),
    ]
